CREATE TABLE distribuidora_item (
	id_item INTEGER NOT NULL,
	distribuidora TEXT NOT NULL,
	
	PRIMARY KEY (id_item, distribuidora),
	FOREIGN KEY (id_item) REFERENCES item_catalogo(id) ON DELETE CASCADE
);

insert into distribuidora_item (id_item, distribuidora) values (1, 'Farrell, Schuppe and Cummerata');
insert into distribuidora_item (id_item, distribuidora) values (2, 'Sanford, Howe and Marquardt');
insert into distribuidora_item (id_item, distribuidora) values (3, 'Runolfsson, Koelpin and Reinger');
insert into distribuidora_item (id_item, distribuidora) values (4, 'Monahan, Zemlak and Buckridge');
insert into distribuidora_item (id_item, distribuidora) values (5, 'Hodkiewicz, Shanahan and Auer');
insert into distribuidora_item (id_item, distribuidora) values (6, 'Nikolaus-Batz');
insert into distribuidora_item (id_item, distribuidora) values (7, 'Ritchie Inc');
insert into distribuidora_item (id_item, distribuidora) values (8, 'Monahan and Sons');
insert into distribuidora_item (id_item, distribuidora) values (9, 'Haley, Bergstrom and Adams');
insert into distribuidora_item (id_item, distribuidora) values (10, 'Beer, Ruecker and Wisozk');
insert into distribuidora_item (id_item, distribuidora) values (11, 'Marks-Bode');
insert into distribuidora_item (id_item, distribuidora) values (12, 'Vandervort Inc');
insert into distribuidora_item (id_item, distribuidora) values (13, 'Sipes LLC');
insert into distribuidora_item (id_item, distribuidora) values (14, 'Flatley LLC');
insert into distribuidora_item (id_item, distribuidora) values (15, 'Fisher, Osinski and West');
insert into distribuidora_item (id_item, distribuidora) values (16, 'Hickle, Legros and Romaguera');
insert into distribuidora_item (id_item, distribuidora) values (17, 'Baumbach, Rolfson and Watsica');
insert into distribuidora_item (id_item, distribuidora) values (18, 'Gutmann, Kuhic and Prosacco');
insert into distribuidora_item (id_item, distribuidora) values (19, 'Labadie, Conroy and Kohler');
insert into distribuidora_item (id_item, distribuidora) values (20, 'Connelly, Daugherty and Harvey');
insert into distribuidora_item (id_item, distribuidora) values (21, 'Raynor LLC');
insert into distribuidora_item (id_item, distribuidora) values (22, 'Bahringer-Larkin');
insert into distribuidora_item (id_item, distribuidora) values (23, 'Rau and Sons');
insert into distribuidora_item (id_item, distribuidora) values (24, 'Padberg-Hickle');
insert into distribuidora_item (id_item, distribuidora) values (25, 'Pollich Inc');
insert into distribuidora_item (id_item, distribuidora) values (26, 'Rempel, McDermott and Murray');
insert into distribuidora_item (id_item, distribuidora) values (27, 'Koch, Nienow and Price');
insert into distribuidora_item (id_item, distribuidora) values (28, 'Rath-Zemlak');
insert into distribuidora_item (id_item, distribuidora) values (29, 'Von-McCullough');
insert into distribuidora_item (id_item, distribuidora) values (30, 'Runte, Jacobi and Wolf');
insert into distribuidora_item (id_item, distribuidora) values (31, 'Macejkovic and Sons');
insert into distribuidora_item (id_item, distribuidora) values (32, 'Nienow, Lebsack and Predovic');
insert into distribuidora_item (id_item, distribuidora) values (33, 'Bins-McKenzie');
insert into distribuidora_item (id_item, distribuidora) values (34, 'Ortiz-Hammes');
insert into distribuidora_item (id_item, distribuidora) values (35, 'Rath-Huel');
insert into distribuidora_item (id_item, distribuidora) values (36, 'Herzog-Wintheiser');
insert into distribuidora_item (id_item, distribuidora) values (37, 'Bauch and Sons');
insert into distribuidora_item (id_item, distribuidora) values (38, 'Abshire LLC');
insert into distribuidora_item (id_item, distribuidora) values (39, 'Prohaska-Pfannerstill');
insert into distribuidora_item (id_item, distribuidora) values (40, 'Conn-Torphy');
insert into distribuidora_item (id_item, distribuidora) values (41, 'Hauck-Rice');
insert into distribuidora_item (id_item, distribuidora) values (42, 'Runte Group');
insert into distribuidora_item (id_item, distribuidora) values (43, 'Luettgen-Lesch');
insert into distribuidora_item (id_item, distribuidora) values (44, 'Kreiger, Koch and Sawayn');
insert into distribuidora_item (id_item, distribuidora) values (45, 'Daugherty, Howell and Heaney');
insert into distribuidora_item (id_item, distribuidora) values (46, 'Osinski-Botsford');
insert into distribuidora_item (id_item, distribuidora) values (47, 'Krajcik, Green and Rippin');
insert into distribuidora_item (id_item, distribuidora) values (48, 'Greenfelder Inc');
insert into distribuidora_item (id_item, distribuidora) values (49, 'Kessler LLC');
insert into distribuidora_item (id_item, distribuidora) values (50, 'Balistreri Group');
insert into distribuidora_item (id_item, distribuidora) values (51, 'Thiel-Price');
insert into distribuidora_item (id_item, distribuidora) values (52, 'Jaskolski, Breitenberg and Boyle');
insert into distribuidora_item (id_item, distribuidora) values (53, 'Hoppe-Langosh');
insert into distribuidora_item (id_item, distribuidora) values (54, 'Hauck, Ryan and Hodkiewicz');
insert into distribuidora_item (id_item, distribuidora) values (55, 'McKenzie Inc');
insert into distribuidora_item (id_item, distribuidora) values (56, 'Walker LLC');
insert into distribuidora_item (id_item, distribuidora) values (57, 'Weissnat-Grady');
insert into distribuidora_item (id_item, distribuidora) values (58, 'Blanda-Crist');
insert into distribuidora_item (id_item, distribuidora) values (59, 'Jerde, Barton and Will');
insert into distribuidora_item (id_item, distribuidora) values (60, 'Walter Inc');
insert into distribuidora_item (id_item, distribuidora) values (61, 'Harber, Carroll and Steuber');
insert into distribuidora_item (id_item, distribuidora) values (62, 'Sauer-Dach');
insert into distribuidora_item (id_item, distribuidora) values (63, 'Swift Inc');
insert into distribuidora_item (id_item, distribuidora) values (64, 'Ondricka Inc');
insert into distribuidora_item (id_item, distribuidora) values (65, 'Emard, Yost and Herzog');
insert into distribuidora_item (id_item, distribuidora) values (66, 'Schmeler Inc');
insert into distribuidora_item (id_item, distribuidora) values (67, 'Emmerich-Grant');
insert into distribuidora_item (id_item, distribuidora) values (68, 'Breitenberg, Weissnat and Zieme');
insert into distribuidora_item (id_item, distribuidora) values (69, 'Ryan, Keeling and Bayer');
insert into distribuidora_item (id_item, distribuidora) values (70, 'Moen, Luettgen and Wolf');
insert into distribuidora_item (id_item, distribuidora) values (71, 'Kilback-Hermiston');
insert into distribuidora_item (id_item, distribuidora) values (72, 'Bartoletti-Schmidt');
insert into distribuidora_item (id_item, distribuidora) values (73, 'Dare, Tillman and Lindgren');
insert into distribuidora_item (id_item, distribuidora) values (74, 'Pfannerstill-Dooley');
insert into distribuidora_item (id_item, distribuidora) values (75, 'Weber-Cartwright');
insert into distribuidora_item (id_item, distribuidora) values (76, 'Beier, Kiehn and Bashirian');
insert into distribuidora_item (id_item, distribuidora) values (77, 'Adams Group');
insert into distribuidora_item (id_item, distribuidora) values (78, 'Robel, Murray and Ledner');
insert into distribuidora_item (id_item, distribuidora) values (79, 'Cruickshank Inc');
insert into distribuidora_item (id_item, distribuidora) values (80, 'Haag and Sons');
insert into distribuidora_item (id_item, distribuidora) values (81, 'Weimann and Sons');
insert into distribuidora_item (id_item, distribuidora) values (82, 'Runolfsson-Lind');
insert into distribuidora_item (id_item, distribuidora) values (83, 'Roberts, Mueller and Hand');
insert into distribuidora_item (id_item, distribuidora) values (84, 'Ankunding-Kuhlman');
insert into distribuidora_item (id_item, distribuidora) values (85, 'Terry Group');
insert into distribuidora_item (id_item, distribuidora) values (86, 'Moen Inc');
insert into distribuidora_item (id_item, distribuidora) values (87, 'Willms, Friesen and Lueilwitz');
insert into distribuidora_item (id_item, distribuidora) values (88, 'Runolfsson-Schamberger');
insert into distribuidora_item (id_item, distribuidora) values (89, 'Padberg and Sons');
insert into distribuidora_item (id_item, distribuidora) values (90, 'Daniel-Smith');
insert into distribuidora_item (id_item, distribuidora) values (91, 'Bednar, Murazik and Rutherford');
insert into distribuidora_item (id_item, distribuidora) values (92, 'Kuvalis Group');
insert into distribuidora_item (id_item, distribuidora) values (93, 'Schneider Group');
insert into distribuidora_item (id_item, distribuidora) values (94, 'Crooks-Hettinger');
insert into distribuidora_item (id_item, distribuidora) values (95, 'Moen Inc');
insert into distribuidora_item (id_item, distribuidora) values (96, 'Paucek and Sons');
insert into distribuidora_item (id_item, distribuidora) values (97, 'Jacobi, Larkin and Effertz');
insert into distribuidora_item (id_item, distribuidora) values (98, 'Spinka-Feeney');
insert into distribuidora_item (id_item, distribuidora) values (99, 'Kling Inc');
insert into distribuidora_item (id_item, distribuidora) values (100, 'Volkman, Spencer and Zulauf');
insert into distribuidora_item (id_item, distribuidora) values (101, 'Rau LLC');
insert into distribuidora_item (id_item, distribuidora) values (102, 'Lang and Sons');
insert into distribuidora_item (id_item, distribuidora) values (103, 'Waelchi LLC');
insert into distribuidora_item (id_item, distribuidora) values (104, 'Wehner-Lueilwitz');
insert into distribuidora_item (id_item, distribuidora) values (105, 'Schowalter Inc');
insert into distribuidora_item (id_item, distribuidora) values (106, 'Stracke-Hodkiewicz');
insert into distribuidora_item (id_item, distribuidora) values (107, 'Ebert, Trantow and Zemlak');
insert into distribuidora_item (id_item, distribuidora) values (108, 'Bechtelar-Zboncak');
insert into distribuidora_item (id_item, distribuidora) values (109, 'Gleichner, Willms and Bauch');
insert into distribuidora_item (id_item, distribuidora) values (110, 'Kassulke, Anderson and Crist');
insert into distribuidora_item (id_item, distribuidora) values (111, 'Gerlach, Dickens and Yundt');
insert into distribuidora_item (id_item, distribuidora) values (112, 'Huels-Daniel');
insert into distribuidora_item (id_item, distribuidora) values (113, 'Dare-Ondricka');
insert into distribuidora_item (id_item, distribuidora) values (114, 'Waters, Blanda and Corwin');
insert into distribuidora_item (id_item, distribuidora) values (115, 'Oberbrunner-Predovic');
insert into distribuidora_item (id_item, distribuidora) values (116, 'Weber and Sons');
insert into distribuidora_item (id_item, distribuidora) values (117, 'Price-Schamberger');
insert into distribuidora_item (id_item, distribuidora) values (118, 'Wehner, Hegmann and Kozey');
insert into distribuidora_item (id_item, distribuidora) values (119, 'Auer Inc');
insert into distribuidora_item (id_item, distribuidora) values (120, 'Reynolds and Sons');
insert into distribuidora_item (id_item, distribuidora) values (121, 'Ritchie, Legros and Schmeler');
insert into distribuidora_item (id_item, distribuidora) values (122, 'Tromp, Daniel and Herzog');
insert into distribuidora_item (id_item, distribuidora) values (123, 'Bins and Sons');
insert into distribuidora_item (id_item, distribuidora) values (124, 'Marvin, Baumbach and Ferry');
insert into distribuidora_item (id_item, distribuidora) values (125, 'Schamberger-Kiehn');
insert into distribuidora_item (id_item, distribuidora) values (126, 'Quigley-McKenzie');
insert into distribuidora_item (id_item, distribuidora) values (127, 'Leannon, Moore and Hahn');
insert into distribuidora_item (id_item, distribuidora) values (128, 'Cummings, Kohler and Mayert');
insert into distribuidora_item (id_item, distribuidora) values (129, 'Feil Group');
insert into distribuidora_item (id_item, distribuidora) values (130, 'O''Conner-Brown');
insert into distribuidora_item (id_item, distribuidora) values (131, 'Conn LLC');
insert into distribuidora_item (id_item, distribuidora) values (132, 'Ward, Tromp and Ritchie');
insert into distribuidora_item (id_item, distribuidora) values (133, 'Koelpin Group');
insert into distribuidora_item (id_item, distribuidora) values (134, 'Padberg, Hickle and Gorczany');
insert into distribuidora_item (id_item, distribuidora) values (135, 'Raynor-Okuneva');
insert into distribuidora_item (id_item, distribuidora) values (136, 'Miller-Trantow');
insert into distribuidora_item (id_item, distribuidora) values (137, 'Beer LLC');
insert into distribuidora_item (id_item, distribuidora) values (138, 'Schiller, Zemlak and Hackett');
insert into distribuidora_item (id_item, distribuidora) values (139, 'Gleichner Group');
insert into distribuidora_item (id_item, distribuidora) values (140, 'Ortiz Group');
insert into distribuidora_item (id_item, distribuidora) values (141, 'Tromp-Veum');
insert into distribuidora_item (id_item, distribuidora) values (142, 'Ritchie Inc');
insert into distribuidora_item (id_item, distribuidora) values (143, 'Kerluke, Cole and Bechtelar');
insert into distribuidora_item (id_item, distribuidora) values (144, 'Howe-Bauch');
insert into distribuidora_item (id_item, distribuidora) values (145, 'Cormier-Mayert');
insert into distribuidora_item (id_item, distribuidora) values (146, 'Graham, Kreiger and Wilkinson');
insert into distribuidora_item (id_item, distribuidora) values (147, 'Lakin-Haag');
insert into distribuidora_item (id_item, distribuidora) values (148, 'Casper-Huel');
insert into distribuidora_item (id_item, distribuidora) values (149, 'Lindgren Group');
insert into distribuidora_item (id_item, distribuidora) values (150, 'Weber, Schaefer and Volkman');
insert into distribuidora_item (id_item, distribuidora) values (151, 'White LLC');
insert into distribuidora_item (id_item, distribuidora) values (152, 'Predovic LLC');
insert into distribuidora_item (id_item, distribuidora) values (153, 'Kshlerin and Sons');
insert into distribuidora_item (id_item, distribuidora) values (154, 'Cruickshank, Veum and Brekke');
insert into distribuidora_item (id_item, distribuidora) values (155, 'Dach Group');
insert into distribuidora_item (id_item, distribuidora) values (156, 'Heathcote, Langosh and Koelpin');
insert into distribuidora_item (id_item, distribuidora) values (157, 'Grant-Braun');
insert into distribuidora_item (id_item, distribuidora) values (158, 'Aufderhar-Heidenreich');
insert into distribuidora_item (id_item, distribuidora) values (159, 'Kirlin LLC');
insert into distribuidora_item (id_item, distribuidora) values (160, 'Becker, Bergstrom and Goldner');
insert into distribuidora_item (id_item, distribuidora) values (161, 'Wuckert, O''Hara and Gutmann');
insert into distribuidora_item (id_item, distribuidora) values (162, 'Goyette, Powlowski and Rempel');
insert into distribuidora_item (id_item, distribuidora) values (163, 'Bradtke and Sons');
insert into distribuidora_item (id_item, distribuidora) values (164, 'Crooks Group');
insert into distribuidora_item (id_item, distribuidora) values (165, 'Herman-Carter');
insert into distribuidora_item (id_item, distribuidora) values (166, 'Wilderman-Quigley');
insert into distribuidora_item (id_item, distribuidora) values (167, 'Champlin-Erdman');
insert into distribuidora_item (id_item, distribuidora) values (168, 'D''Amore, Torp and Kunze');
insert into distribuidora_item (id_item, distribuidora) values (169, 'Bahringer Inc');
insert into distribuidora_item (id_item, distribuidora) values (170, 'Armstrong LLC');
insert into distribuidora_item (id_item, distribuidora) values (171, 'Boyle, McKenzie and Balistreri');
insert into distribuidora_item (id_item, distribuidora) values (172, 'Mosciski, Walsh and Ward');
insert into distribuidora_item (id_item, distribuidora) values (173, 'Spencer, Muller and Schiller');
insert into distribuidora_item (id_item, distribuidora) values (174, 'Tillman Group');
insert into distribuidora_item (id_item, distribuidora) values (175, 'Stark-Deckow');
insert into distribuidora_item (id_item, distribuidora) values (176, 'Sauer Group');
insert into distribuidora_item (id_item, distribuidora) values (177, 'Harris, Strosin and Gutkowski');
insert into distribuidora_item (id_item, distribuidora) values (178, 'Braun Inc');
insert into distribuidora_item (id_item, distribuidora) values (179, 'Nienow, Ziemann and Kihn');
insert into distribuidora_item (id_item, distribuidora) values (180, 'Lueilwitz LLC');
insert into distribuidora_item (id_item, distribuidora) values (181, 'Nikolaus LLC');
insert into distribuidora_item (id_item, distribuidora) values (182, 'Champlin-Grimes');
insert into distribuidora_item (id_item, distribuidora) values (183, 'Medhurst LLC');
insert into distribuidora_item (id_item, distribuidora) values (184, 'Dibbert-Dicki');
insert into distribuidora_item (id_item, distribuidora) values (185, 'Lemke-Roob');
insert into distribuidora_item (id_item, distribuidora) values (186, 'Haley-Wiegand');
insert into distribuidora_item (id_item, distribuidora) values (187, 'Durgan Group');
insert into distribuidora_item (id_item, distribuidora) values (188, 'Larkin-Wyman');
insert into distribuidora_item (id_item, distribuidora) values (189, 'Toy Group');
insert into distribuidora_item (id_item, distribuidora) values (190, 'Becker and Sons');
insert into distribuidora_item (id_item, distribuidora) values (191, 'Schneider, Blanda and Ratke');
insert into distribuidora_item (id_item, distribuidora) values (192, 'Oberbrunner-Schultz');
insert into distribuidora_item (id_item, distribuidora) values (193, 'Kling, Murray and Huels');
insert into distribuidora_item (id_item, distribuidora) values (194, 'Murazik-Barrows');
insert into distribuidora_item (id_item, distribuidora) values (195, 'Wehner LLC');
insert into distribuidora_item (id_item, distribuidora) values (196, 'Conn Inc');
insert into distribuidora_item (id_item, distribuidora) values (197, 'Hahn-Kihn');
insert into distribuidora_item (id_item, distribuidora) values (198, 'Terry Group');
insert into distribuidora_item (id_item, distribuidora) values (199, 'Zemlak, Adams and Ledner');
insert into distribuidora_item (id_item, distribuidora) values (200, 'DuBuque, Braun and Douglas');
insert into distribuidora_item (id_item, distribuidora) values (201, 'Franecki and Sons');
insert into distribuidora_item (id_item, distribuidora) values (202, 'Stokes, Hoeger and West');
insert into distribuidora_item (id_item, distribuidora) values (203, 'Ziemann, Kuhic and Senger');
insert into distribuidora_item (id_item, distribuidora) values (204, 'Kovacek-Maggio');
insert into distribuidora_item (id_item, distribuidora) values (205, 'Walsh, Kris and Gleason');
insert into distribuidora_item (id_item, distribuidora) values (206, 'Windler-Fritsch');
insert into distribuidora_item (id_item, distribuidora) values (207, 'Klein Inc');
insert into distribuidora_item (id_item, distribuidora) values (208, 'Haley-Cartwright');
insert into distribuidora_item (id_item, distribuidora) values (209, 'Gibson, Herzog and Spencer');
insert into distribuidora_item (id_item, distribuidora) values (210, 'Schneider-Quigley');
insert into distribuidora_item (id_item, distribuidora) values (211, 'Thompson-Greenholt');
insert into distribuidora_item (id_item, distribuidora) values (212, 'Mosciski-Heidenreich');
insert into distribuidora_item (id_item, distribuidora) values (213, 'Ortiz-Considine');
insert into distribuidora_item (id_item, distribuidora) values (214, 'Hodkiewicz Group');
insert into distribuidora_item (id_item, distribuidora) values (215, 'Lehner Group');
insert into distribuidora_item (id_item, distribuidora) values (216, 'Parisian-Hackett');
insert into distribuidora_item (id_item, distribuidora) values (217, 'Von Inc');
insert into distribuidora_item (id_item, distribuidora) values (218, 'Braun Inc');
insert into distribuidora_item (id_item, distribuidora) values (219, 'Tremblay-Feeney');
insert into distribuidora_item (id_item, distribuidora) values (220, 'Hilll, Harris and Rogahn');
insert into distribuidora_item (id_item, distribuidora) values (221, 'Ward, Wunsch and Berge');
insert into distribuidora_item (id_item, distribuidora) values (222, 'Johnson, Shields and Stokes');
insert into distribuidora_item (id_item, distribuidora) values (223, 'Sanford, Thompson and Heathcote');
insert into distribuidora_item (id_item, distribuidora) values (224, 'Morar Inc');
insert into distribuidora_item (id_item, distribuidora) values (225, 'Medhurst-Kihn');
insert into distribuidora_item (id_item, distribuidora) values (226, 'Purdy-Daugherty');
insert into distribuidora_item (id_item, distribuidora) values (227, 'Miller, Waelchi and Rippin');
insert into distribuidora_item (id_item, distribuidora) values (228, 'McCullough LLC');
insert into distribuidora_item (id_item, distribuidora) values (229, 'Hamill-Kreiger');
insert into distribuidora_item (id_item, distribuidora) values (230, 'Gibson-Cole');
insert into distribuidora_item (id_item, distribuidora) values (231, 'Emmerich Inc');
insert into distribuidora_item (id_item, distribuidora) values (232, 'Cronin Inc');
insert into distribuidora_item (id_item, distribuidora) values (233, 'Altenwerth LLC');
insert into distribuidora_item (id_item, distribuidora) values (234, 'Kozey-Leffler');
insert into distribuidora_item (id_item, distribuidora) values (235, 'Cummings, Schumm and Senger');
insert into distribuidora_item (id_item, distribuidora) values (236, 'Cremin, Carter and Denesik');
insert into distribuidora_item (id_item, distribuidora) values (237, 'Rodriguez, Bergstrom and Hamill');
insert into distribuidora_item (id_item, distribuidora) values (238, 'Vandervort-Stehr');
insert into distribuidora_item (id_item, distribuidora) values (239, 'Hackett, Veum and Price');
insert into distribuidora_item (id_item, distribuidora) values (240, 'Nienow, Schultz and Hagenes');
insert into distribuidora_item (id_item, distribuidora) values (241, 'Witting-Rempel');
insert into distribuidora_item (id_item, distribuidora) values (242, 'Stehr and Sons');
insert into distribuidora_item (id_item, distribuidora) values (243, 'Hegmann LLC');
insert into distribuidora_item (id_item, distribuidora) values (244, 'Bogan LLC');
insert into distribuidora_item (id_item, distribuidora) values (245, 'Hodkiewicz and Sons');
insert into distribuidora_item (id_item, distribuidora) values (246, 'Schulist and Sons');
insert into distribuidora_item (id_item, distribuidora) values (247, 'Mante, Murphy and Gutmann');
insert into distribuidora_item (id_item, distribuidora) values (248, 'Heaney Group');
insert into distribuidora_item (id_item, distribuidora) values (249, 'Botsford-Stracke');
insert into distribuidora_item (id_item, distribuidora) values (250, 'Bailey Inc');
insert into distribuidora_item (id_item, distribuidora) values (251, 'Kuhlman-Monahan');
insert into distribuidora_item (id_item, distribuidora) values (252, 'Hammes, Halvorson and Parisian');
insert into distribuidora_item (id_item, distribuidora) values (253, 'Zemlak-Bogisich');
insert into distribuidora_item (id_item, distribuidora) values (254, 'Sporer-Willms');
insert into distribuidora_item (id_item, distribuidora) values (255, 'Doyle Group');
insert into distribuidora_item (id_item, distribuidora) values (256, 'Turcotte and Sons');
insert into distribuidora_item (id_item, distribuidora) values (257, 'Bauch, Wyman and Murray');
insert into distribuidora_item (id_item, distribuidora) values (258, 'Wehner and Sons');
insert into distribuidora_item (id_item, distribuidora) values (259, 'Rodriguez, Daniel and Spinka');
insert into distribuidora_item (id_item, distribuidora) values (260, 'Herzog-Hettinger');
insert into distribuidora_item (id_item, distribuidora) values (261, 'Jakubowski-Tremblay');
insert into distribuidora_item (id_item, distribuidora) values (262, 'Hackett, Waters and Monahan');
insert into distribuidora_item (id_item, distribuidora) values (263, 'Lubowitz, Carter and Abbott');
insert into distribuidora_item (id_item, distribuidora) values (264, 'Beatty, Cummerata and Legros');
insert into distribuidora_item (id_item, distribuidora) values (265, 'Nikolaus-Parker');
insert into distribuidora_item (id_item, distribuidora) values (266, 'Sauer, Kiehn and Keeling');
insert into distribuidora_item (id_item, distribuidora) values (267, 'Will LLC');
insert into distribuidora_item (id_item, distribuidora) values (268, 'Walsh Group');
insert into distribuidora_item (id_item, distribuidora) values (269, 'Lynch-Lang');
insert into distribuidora_item (id_item, distribuidora) values (270, 'Christiansen-Adams');
insert into distribuidora_item (id_item, distribuidora) values (271, 'Hayes, Sauer and Boyer');
insert into distribuidora_item (id_item, distribuidora) values (272, 'Kuvalis LLC');
insert into distribuidora_item (id_item, distribuidora) values (273, 'Durgan-Witting');
insert into distribuidora_item (id_item, distribuidora) values (274, 'O''Keefe LLC');
insert into distribuidora_item (id_item, distribuidora) values (275, 'Runolfsson Inc');
insert into distribuidora_item (id_item, distribuidora) values (276, 'Gerhold-Leannon');
insert into distribuidora_item (id_item, distribuidora) values (277, 'Ritchie, Nader and Gleason');
insert into distribuidora_item (id_item, distribuidora) values (278, 'Aufderhar, Smith and Thompson');
insert into distribuidora_item (id_item, distribuidora) values (279, 'Gutkowski-Gottlieb');
insert into distribuidora_item (id_item, distribuidora) values (280, 'Wolff LLC');
insert into distribuidora_item (id_item, distribuidora) values (281, 'Tremblay and Sons');
insert into distribuidora_item (id_item, distribuidora) values (282, 'Mertz Group');
insert into distribuidora_item (id_item, distribuidora) values (283, 'Pfeffer-Nolan');
insert into distribuidora_item (id_item, distribuidora) values (284, 'Parker Inc');
insert into distribuidora_item (id_item, distribuidora) values (285, 'Hand-Hartmann');
insert into distribuidora_item (id_item, distribuidora) values (286, 'Prosacco, Sauer and Reinger');
insert into distribuidora_item (id_item, distribuidora) values (287, 'Ortiz, Stark and Raynor');
insert into distribuidora_item (id_item, distribuidora) values (288, 'Gorczany-Kovacek');
insert into distribuidora_item (id_item, distribuidora) values (289, 'Kiehn-O''Reilly');
insert into distribuidora_item (id_item, distribuidora) values (290, 'O''Conner, Farrell and Kuvalis');
insert into distribuidora_item (id_item, distribuidora) values (291, 'Lubowitz, Cronin and Marquardt');
insert into distribuidora_item (id_item, distribuidora) values (292, 'Crona LLC');
insert into distribuidora_item (id_item, distribuidora) values (293, 'Schuster, Kris and Nicolas');
insert into distribuidora_item (id_item, distribuidora) values (294, 'Krajcik Inc');
insert into distribuidora_item (id_item, distribuidora) values (295, 'Reichel, Kirlin and Langworth');
insert into distribuidora_item (id_item, distribuidora) values (296, 'Dare, Haley and Rosenbaum');
insert into distribuidora_item (id_item, distribuidora) values (297, 'Robel, Hansen and Huels');
insert into distribuidora_item (id_item, distribuidora) values (298, 'Pacocha, Ziemann and Ankunding');
insert into distribuidora_item (id_item, distribuidora) values (299, 'Considine Inc');
insert into distribuidora_item (id_item, distribuidora) values (300, 'Gottlieb, Schoen and Bechtelar');
insert into distribuidora_item (id_item, distribuidora) values (301, 'Weissnat Group');
insert into distribuidora_item (id_item, distribuidora) values (302, 'Metz LLC');
insert into distribuidora_item (id_item, distribuidora) values (303, 'Medhurst and Sons');
insert into distribuidora_item (id_item, distribuidora) values (304, 'Huels Inc');
insert into distribuidora_item (id_item, distribuidora) values (305, 'Rau-Mayert');
insert into distribuidora_item (id_item, distribuidora) values (306, 'Bins-Reynolds');
insert into distribuidora_item (id_item, distribuidora) values (307, 'Durgan, Krajcik and Conn');
insert into distribuidora_item (id_item, distribuidora) values (308, 'Morar, Gusikowski and Marks');
insert into distribuidora_item (id_item, distribuidora) values (309, 'Rutherford and Sons');
insert into distribuidora_item (id_item, distribuidora) values (310, 'Bergstrom Group');
insert into distribuidora_item (id_item, distribuidora) values (311, 'Kemmer, Wunsch and Zemlak');
insert into distribuidora_item (id_item, distribuidora) values (312, 'Watsica, McClure and Windler');
insert into distribuidora_item (id_item, distribuidora) values (313, 'Feest, Bosco and Wilkinson');
insert into distribuidora_item (id_item, distribuidora) values (314, 'Douglas-Kulas');
insert into distribuidora_item (id_item, distribuidora) values (315, 'Rempel, White and Hoeger');
insert into distribuidora_item (id_item, distribuidora) values (316, 'Abbott, Lind and Krajcik');
insert into distribuidora_item (id_item, distribuidora) values (317, 'Vandervort Group');
insert into distribuidora_item (id_item, distribuidora) values (318, 'Wilderman and Sons');
insert into distribuidora_item (id_item, distribuidora) values (319, 'Hickle LLC');
insert into distribuidora_item (id_item, distribuidora) values (320, 'Brown, Marks and Buckridge');
insert into distribuidora_item (id_item, distribuidora) values (321, 'Mraz and Sons');
insert into distribuidora_item (id_item, distribuidora) values (322, 'Lubowitz, Volkman and Cormier');
insert into distribuidora_item (id_item, distribuidora) values (323, 'Gusikowski Inc');
insert into distribuidora_item (id_item, distribuidora) values (324, 'Schuppe-Lesch');
insert into distribuidora_item (id_item, distribuidora) values (325, 'Homenick-Kub');
insert into distribuidora_item (id_item, distribuidora) values (326, 'Quigley-Jacobson');
insert into distribuidora_item (id_item, distribuidora) values (327, 'Considine, Bednar and Carter');
insert into distribuidora_item (id_item, distribuidora) values (328, 'Brown-Rogahn');
insert into distribuidora_item (id_item, distribuidora) values (329, 'Klocko, Kris and Steuber');
insert into distribuidora_item (id_item, distribuidora) values (330, 'Sanford, Weimann and Rice');
insert into distribuidora_item (id_item, distribuidora) values (331, 'Cormier Inc');
insert into distribuidora_item (id_item, distribuidora) values (332, 'Nikolaus-Lockman');
insert into distribuidora_item (id_item, distribuidora) values (333, 'D''Amore-Nolan');
insert into distribuidora_item (id_item, distribuidora) values (334, 'Quitzon Inc');
insert into distribuidora_item (id_item, distribuidora) values (335, 'Kreiger, O''Kon and Fahey');
insert into distribuidora_item (id_item, distribuidora) values (336, 'Renner, Stanton and Cartwright');
insert into distribuidora_item (id_item, distribuidora) values (337, 'Ondricka LLC');
insert into distribuidora_item (id_item, distribuidora) values (338, 'O''Reilly Inc');
insert into distribuidora_item (id_item, distribuidora) values (339, 'Bode LLC');
insert into distribuidora_item (id_item, distribuidora) values (340, 'Pouros LLC');
insert into distribuidora_item (id_item, distribuidora) values (341, 'Kunze, Becker and Oberbrunner');
insert into distribuidora_item (id_item, distribuidora) values (342, 'Boehm-Koepp');
insert into distribuidora_item (id_item, distribuidora) values (343, 'Parisian Inc');
insert into distribuidora_item (id_item, distribuidora) values (344, 'Wiza-Stroman');
insert into distribuidora_item (id_item, distribuidora) values (345, 'Auer, Runolfsdottir and Schaden');
insert into distribuidora_item (id_item, distribuidora) values (346, 'Dicki and Sons');
insert into distribuidora_item (id_item, distribuidora) values (347, 'Stroman Inc');
insert into distribuidora_item (id_item, distribuidora) values (348, 'Wolf LLC');
insert into distribuidora_item (id_item, distribuidora) values (349, 'Sanford, Bayer and Wiza');
insert into distribuidora_item (id_item, distribuidora) values (350, 'Wuckert-Schiller');
insert into distribuidora_item (id_item, distribuidora) values (351, 'Cummings-Corkery');
insert into distribuidora_item (id_item, distribuidora) values (352, 'Maggio, Hermann and Stark');
insert into distribuidora_item (id_item, distribuidora) values (353, 'Botsford, Effertz and Barrows');
insert into distribuidora_item (id_item, distribuidora) values (354, 'Mante, Cremin and Lynch');
insert into distribuidora_item (id_item, distribuidora) values (355, 'Hyatt, Herman and Rohan');
insert into distribuidora_item (id_item, distribuidora) values (356, 'Boehm, Kautzer and Reynolds');
insert into distribuidora_item (id_item, distribuidora) values (357, 'Rosenbaum, Herzog and Cremin');
insert into distribuidora_item (id_item, distribuidora) values (358, 'Mosciski and Sons');
insert into distribuidora_item (id_item, distribuidora) values (359, 'Paucek Inc');
insert into distribuidora_item (id_item, distribuidora) values (360, 'Fritsch, Simonis and Schoen');
insert into distribuidora_item (id_item, distribuidora) values (361, 'Osinski-Kozey');
insert into distribuidora_item (id_item, distribuidora) values (362, 'Gottlieb and Sons');
insert into distribuidora_item (id_item, distribuidora) values (363, 'Franecki, Schuster and Zemlak');
insert into distribuidora_item (id_item, distribuidora) values (364, 'Cormier, O''Kon and Lakin');
insert into distribuidora_item (id_item, distribuidora) values (365, 'Kutch Group');
insert into distribuidora_item (id_item, distribuidora) values (366, 'Skiles, Kuhn and Padberg');
insert into distribuidora_item (id_item, distribuidora) values (367, 'Balistreri-Cassin');
insert into distribuidora_item (id_item, distribuidora) values (368, 'Grimes, Buckridge and Daugherty');
insert into distribuidora_item (id_item, distribuidora) values (369, 'Stoltenberg-Marvin');
insert into distribuidora_item (id_item, distribuidora) values (370, 'Greenholt and Sons');
insert into distribuidora_item (id_item, distribuidora) values (371, 'Braun Inc');
insert into distribuidora_item (id_item, distribuidora) values (372, 'Littel-Renner');
insert into distribuidora_item (id_item, distribuidora) values (373, 'Doyle and Sons');
insert into distribuidora_item (id_item, distribuidora) values (374, 'Hessel LLC');
insert into distribuidora_item (id_item, distribuidora) values (375, 'Blick LLC');
insert into distribuidora_item (id_item, distribuidora) values (376, 'Hodkiewicz-Prosacco');
insert into distribuidora_item (id_item, distribuidora) values (377, 'West-Lynch');
insert into distribuidora_item (id_item, distribuidora) values (378, 'Renner, Cartwright and Koch');
insert into distribuidora_item (id_item, distribuidora) values (379, 'Huel, Borer and Nienow');
insert into distribuidora_item (id_item, distribuidora) values (380, 'Larson LLC');
insert into distribuidora_item (id_item, distribuidora) values (381, 'Beahan, Oberbrunner and Gleason');
insert into distribuidora_item (id_item, distribuidora) values (382, 'Welch LLC');
insert into distribuidora_item (id_item, distribuidora) values (383, 'Schuppe, Kessler and Beer');
insert into distribuidora_item (id_item, distribuidora) values (384, 'Bosco, Skiles and Kirlin');
insert into distribuidora_item (id_item, distribuidora) values (385, 'Glover LLC');
insert into distribuidora_item (id_item, distribuidora) values (386, 'Kub, Crist and Kulas');
insert into distribuidora_item (id_item, distribuidora) values (387, 'Powlowski-Walsh');
insert into distribuidora_item (id_item, distribuidora) values (388, 'Frami-McLaughlin');
insert into distribuidora_item (id_item, distribuidora) values (389, 'Schuster, Zemlak and Ferry');
insert into distribuidora_item (id_item, distribuidora) values (390, 'Larkin, Mayer and Barton');
insert into distribuidora_item (id_item, distribuidora) values (391, 'Prosacco-Howe');
insert into distribuidora_item (id_item, distribuidora) values (392, 'Bashirian, Nolan and Dach');
insert into distribuidora_item (id_item, distribuidora) values (393, 'Kohler and Sons');
insert into distribuidora_item (id_item, distribuidora) values (394, 'Hermann-Wyman');
insert into distribuidora_item (id_item, distribuidora) values (395, 'Nitzsche, Shanahan and Gerlach');
insert into distribuidora_item (id_item, distribuidora) values (396, 'Heller Inc');
insert into distribuidora_item (id_item, distribuidora) values (397, 'Jones LLC');
insert into distribuidora_item (id_item, distribuidora) values (398, 'Mosciski Inc');
insert into distribuidora_item (id_item, distribuidora) values (399, 'Dare LLC');
insert into distribuidora_item (id_item, distribuidora) values (400, 'Murazik-Von');
insert into distribuidora_item (id_item, distribuidora) values (401, 'Moore, Abbott and Russel');
insert into distribuidora_item (id_item, distribuidora) values (402, 'Prosacco-Crooks');
insert into distribuidora_item (id_item, distribuidora) values (403, 'Keebler Inc');
insert into distribuidora_item (id_item, distribuidora) values (404, 'Kuhlman, Bosco and Feeney');
insert into distribuidora_item (id_item, distribuidora) values (405, 'Tremblay Group');
insert into distribuidora_item (id_item, distribuidora) values (406, 'Bergnaum and Sons');
insert into distribuidora_item (id_item, distribuidora) values (407, 'Jones, Reichert and Hudson');
insert into distribuidora_item (id_item, distribuidora) values (408, 'Funk-Ernser');
insert into distribuidora_item (id_item, distribuidora) values (409, 'Schinner and Sons');
insert into distribuidora_item (id_item, distribuidora) values (410, 'Kerluke LLC');
insert into distribuidora_item (id_item, distribuidora) values (411, 'Langworth and Sons');
insert into distribuidora_item (id_item, distribuidora) values (412, 'Buckridge, Dietrich and Beier');
insert into distribuidora_item (id_item, distribuidora) values (413, 'Halvorson Group');
insert into distribuidora_item (id_item, distribuidora) values (414, 'Bogan-Toy');
insert into distribuidora_item (id_item, distribuidora) values (415, 'Grimes-Daniel');
insert into distribuidora_item (id_item, distribuidora) values (416, 'Nitzsche, Christiansen and McLaughlin');
insert into distribuidora_item (id_item, distribuidora) values (417, 'Wehner-Hegmann');
insert into distribuidora_item (id_item, distribuidora) values (418, 'Waters-Goldner');
insert into distribuidora_item (id_item, distribuidora) values (419, 'Jacobi LLC');
insert into distribuidora_item (id_item, distribuidora) values (420, 'Durgan-Frami');
insert into distribuidora_item (id_item, distribuidora) values (421, 'Kautzer and Sons');
insert into distribuidora_item (id_item, distribuidora) values (422, 'Luettgen-Hahn');
insert into distribuidora_item (id_item, distribuidora) values (423, 'Gleichner, O''Connell and Labadie');
insert into distribuidora_item (id_item, distribuidora) values (424, 'Senger LLC');
insert into distribuidora_item (id_item, distribuidora) values (425, 'Zboncak Inc');
insert into distribuidora_item (id_item, distribuidora) values (426, 'Yundt-Hamill');
insert into distribuidora_item (id_item, distribuidora) values (427, 'Huels LLC');
insert into distribuidora_item (id_item, distribuidora) values (428, 'Johnston-Murphy');
insert into distribuidora_item (id_item, distribuidora) values (429, 'Schamberger, Flatley and Blanda');
insert into distribuidora_item (id_item, distribuidora) values (430, 'Stehr Inc');
insert into distribuidora_item (id_item, distribuidora) values (431, 'Lakin, Kohler and Koepp');
insert into distribuidora_item (id_item, distribuidora) values (432, 'Pollich, Jenkins and Johnson');
insert into distribuidora_item (id_item, distribuidora) values (433, 'Ward, Witting and Stracke');
insert into distribuidora_item (id_item, distribuidora) values (434, 'Bartell, Schimmel and Kub');
insert into distribuidora_item (id_item, distribuidora) values (435, 'Gerlach-Pacocha');
insert into distribuidora_item (id_item, distribuidora) values (436, 'Leannon, Jacobi and Daniel');
insert into distribuidora_item (id_item, distribuidora) values (437, 'West and Sons');
insert into distribuidora_item (id_item, distribuidora) values (438, 'Williamson, Moen and Marquardt');
insert into distribuidora_item (id_item, distribuidora) values (439, 'Bins and Sons');
insert into distribuidora_item (id_item, distribuidora) values (440, 'Schaden Group');
insert into distribuidora_item (id_item, distribuidora) values (441, 'Christiansen, Heller and Runolfsdottir');
insert into distribuidora_item (id_item, distribuidora) values (442, 'Corkery, Rutherford and Rutherford');
insert into distribuidora_item (id_item, distribuidora) values (443, 'Kerluke, Olson and Osinski');
insert into distribuidora_item (id_item, distribuidora) values (444, 'Stanton, Lueilwitz and Quitzon');
insert into distribuidora_item (id_item, distribuidora) values (445, 'Waelchi-Koch');
insert into distribuidora_item (id_item, distribuidora) values (446, 'Mohr Group');
insert into distribuidora_item (id_item, distribuidora) values (447, 'Vandervort and Sons');
insert into distribuidora_item (id_item, distribuidora) values (448, 'Jacobson, Davis and Cormier');
insert into distribuidora_item (id_item, distribuidora) values (449, 'Wisozk Group');
insert into distribuidora_item (id_item, distribuidora) values (450, 'Leannon, Yost and Abbott');
insert into distribuidora_item (id_item, distribuidora) values (451, 'Shanahan, Doyle and Abshire');
insert into distribuidora_item (id_item, distribuidora) values (452, 'Wunsch-Abshire');
insert into distribuidora_item (id_item, distribuidora) values (453, 'Sawayn Inc');
insert into distribuidora_item (id_item, distribuidora) values (454, 'Schulist-Paucek');
insert into distribuidora_item (id_item, distribuidora) values (455, 'Hermiston, Mohr and Stark');
insert into distribuidora_item (id_item, distribuidora) values (456, 'Medhurst, Halvorson and Prohaska');
insert into distribuidora_item (id_item, distribuidora) values (457, 'Hegmann-Franecki');
insert into distribuidora_item (id_item, distribuidora) values (458, 'Hagenes LLC');
insert into distribuidora_item (id_item, distribuidora) values (459, 'Kovacek Inc');
insert into distribuidora_item (id_item, distribuidora) values (460, 'Klein, Considine and Kuhic');
insert into distribuidora_item (id_item, distribuidora) values (461, 'Mills Group');
insert into distribuidora_item (id_item, distribuidora) values (462, 'O''Conner-Effertz');
insert into distribuidora_item (id_item, distribuidora) values (463, 'Klocko and Sons');
insert into distribuidora_item (id_item, distribuidora) values (464, 'Kuvalis, Larkin and Nitzsche');
insert into distribuidora_item (id_item, distribuidora) values (465, 'Wehner LLC');
insert into distribuidora_item (id_item, distribuidora) values (466, 'Sporer Group');
insert into distribuidora_item (id_item, distribuidora) values (467, 'Toy Group');
insert into distribuidora_item (id_item, distribuidora) values (468, 'Hudson-Zieme');
insert into distribuidora_item (id_item, distribuidora) values (469, 'Ratke-Kuhlman');
insert into distribuidora_item (id_item, distribuidora) values (470, 'Bergnaum-Nitzsche');
insert into distribuidora_item (id_item, distribuidora) values (471, 'Luettgen-Leannon');
insert into distribuidora_item (id_item, distribuidora) values (472, 'Reynolds, Ferry and Lueilwitz');
insert into distribuidora_item (id_item, distribuidora) values (473, 'Mosciski-Fadel');
insert into distribuidora_item (id_item, distribuidora) values (474, 'Kuhlman, Bins and Quigley');
insert into distribuidora_item (id_item, distribuidora) values (475, 'Satterfield, Quigley and Harris');
insert into distribuidora_item (id_item, distribuidora) values (476, 'Stamm Inc');
insert into distribuidora_item (id_item, distribuidora) values (477, 'Brown, Reichel and Reichert');
insert into distribuidora_item (id_item, distribuidora) values (478, 'Hansen, Hegmann and McGlynn');
insert into distribuidora_item (id_item, distribuidora) values (479, 'Schuster LLC');
insert into distribuidora_item (id_item, distribuidora) values (480, 'Mitchell, Powlowski and Gleason');
insert into distribuidora_item (id_item, distribuidora) values (481, 'Rutherford, O''Connell and Anderson');
insert into distribuidora_item (id_item, distribuidora) values (482, 'Reichert Inc');
insert into distribuidora_item (id_item, distribuidora) values (483, 'Koepp-Dickens');
insert into distribuidora_item (id_item, distribuidora) values (484, 'D''Amore-Shields');
insert into distribuidora_item (id_item, distribuidora) values (485, 'Heller Group');
insert into distribuidora_item (id_item, distribuidora) values (486, 'Ernser-Ledner');
insert into distribuidora_item (id_item, distribuidora) values (487, 'Blanda-Skiles');
insert into distribuidora_item (id_item, distribuidora) values (488, 'Ortiz, Pollich and Kihn');
insert into distribuidora_item (id_item, distribuidora) values (489, 'Pollich LLC');
insert into distribuidora_item (id_item, distribuidora) values (490, 'Dietrich-Kuvalis');
insert into distribuidora_item (id_item, distribuidora) values (491, 'Tremblay Inc');
insert into distribuidora_item (id_item, distribuidora) values (492, 'Towne, Crona and Cummings');
insert into distribuidora_item (id_item, distribuidora) values (493, 'Kozey, Gleason and West');
insert into distribuidora_item (id_item, distribuidora) values (494, 'Runolfsson Inc');
insert into distribuidora_item (id_item, distribuidora) values (495, 'Harber-Connelly');
insert into distribuidora_item (id_item, distribuidora) values (496, 'Huel LLC');
insert into distribuidora_item (id_item, distribuidora) values (497, 'Hudson-Pfeffer');
insert into distribuidora_item (id_item, distribuidora) values (498, 'Adams, Howell and Rempel');
insert into distribuidora_item (id_item, distribuidora) values (499, 'Gorczany Group');
insert into distribuidora_item (id_item, distribuidora) values (500, 'Schultz and Sons');
insert into distribuidora_item (id_item, distribuidora) values (501, 'Yost Group');
insert into distribuidora_item (id_item, distribuidora) values (502, 'Hoppe, Schultz and Fahey');
insert into distribuidora_item (id_item, distribuidora) values (503, 'Terry, Oberbrunner and Von');
insert into distribuidora_item (id_item, distribuidora) values (504, 'Steuber-Beier');
insert into distribuidora_item (id_item, distribuidora) values (505, 'Fisher Inc');
insert into distribuidora_item (id_item, distribuidora) values (506, 'McDermott-Little');
insert into distribuidora_item (id_item, distribuidora) values (507, 'Wehner Inc');
insert into distribuidora_item (id_item, distribuidora) values (508, 'Ankunding and Sons');
insert into distribuidora_item (id_item, distribuidora) values (509, 'Rowe-Metz');
insert into distribuidora_item (id_item, distribuidora) values (510, 'Rempel LLC');
insert into distribuidora_item (id_item, distribuidora) values (511, 'Reilly, Keeling and Jerde');
insert into distribuidora_item (id_item, distribuidora) values (512, 'Stanton, Toy and O''Hara');
insert into distribuidora_item (id_item, distribuidora) values (513, 'Bashirian-Cummings');
insert into distribuidora_item (id_item, distribuidora) values (514, 'Moore, Botsford and Braun');
insert into distribuidora_item (id_item, distribuidora) values (515, 'Franecki, Monahan and Funk');
insert into distribuidora_item (id_item, distribuidora) values (516, 'Barton-Roob');
insert into distribuidora_item (id_item, distribuidora) values (517, 'Hodkiewicz, Sanford and Deckow');
insert into distribuidora_item (id_item, distribuidora) values (518, 'Mueller LLC');
insert into distribuidora_item (id_item, distribuidora) values (519, 'Yundt and Sons');
insert into distribuidora_item (id_item, distribuidora) values (520, 'Kohler Inc');
insert into distribuidora_item (id_item, distribuidora) values (521, 'Rowe, Dare and Gottlieb');
insert into distribuidora_item (id_item, distribuidora) values (522, 'Sauer, Hills and Gerlach');
insert into distribuidora_item (id_item, distribuidora) values (523, 'Gleichner LLC');
insert into distribuidora_item (id_item, distribuidora) values (524, 'Blanda-Powlowski');
insert into distribuidora_item (id_item, distribuidora) values (525, 'Bashirian, O''Reilly and Gusikowski');
insert into distribuidora_item (id_item, distribuidora) values (526, 'Shields, Moore and Kshlerin');
insert into distribuidora_item (id_item, distribuidora) values (527, 'Rohan Inc');
insert into distribuidora_item (id_item, distribuidora) values (528, 'Jacobi, Mertz and Mosciski');
insert into distribuidora_item (id_item, distribuidora) values (529, 'Boehm, Ryan and Hirthe');
insert into distribuidora_item (id_item, distribuidora) values (530, 'Zulauf, Kuhic and Herzog');
insert into distribuidora_item (id_item, distribuidora) values (531, 'Huel and Sons');
insert into distribuidora_item (id_item, distribuidora) values (532, 'Kozey-Goodwin');
insert into distribuidora_item (id_item, distribuidora) values (533, 'Turcotte and Sons');
insert into distribuidora_item (id_item, distribuidora) values (534, 'West LLC');
insert into distribuidora_item (id_item, distribuidora) values (535, 'Morar-Abernathy');
insert into distribuidora_item (id_item, distribuidora) values (536, 'Von, Brakus and Mraz');
insert into distribuidora_item (id_item, distribuidora) values (537, 'Schaden, Goodwin and Romaguera');
insert into distribuidora_item (id_item, distribuidora) values (538, 'Mosciski, Zulauf and Doyle');
insert into distribuidora_item (id_item, distribuidora) values (539, 'Gleichner, Pacocha and Schowalter');
insert into distribuidora_item (id_item, distribuidora) values (540, 'Barton, Lang and MacGyver');
insert into distribuidora_item (id_item, distribuidora) values (541, 'Gusikowski Inc');
insert into distribuidora_item (id_item, distribuidora) values (542, 'Steuber, Krajcik and Armstrong');
insert into distribuidora_item (id_item, distribuidora) values (543, 'Legros-Breitenberg');
insert into distribuidora_item (id_item, distribuidora) values (544, 'Gibson-Morissette');
insert into distribuidora_item (id_item, distribuidora) values (545, 'Hartmann-Douglas');
insert into distribuidora_item (id_item, distribuidora) values (546, 'McDermott-Ledner');
insert into distribuidora_item (id_item, distribuidora) values (547, 'Mueller-Kunze');
insert into distribuidora_item (id_item, distribuidora) values (548, 'Lakin, Wiegand and Swaniawski');
insert into distribuidora_item (id_item, distribuidora) values (549, 'Schuster, Wisoky and West');
insert into distribuidora_item (id_item, distribuidora) values (550, 'Donnelly, Will and Lynch');
insert into distribuidora_item (id_item, distribuidora) values (551, 'Bogisich and Sons');
insert into distribuidora_item (id_item, distribuidora) values (552, 'Sauer Group');
insert into distribuidora_item (id_item, distribuidora) values (553, 'McKenzie, Ruecker and Smitham');
insert into distribuidora_item (id_item, distribuidora) values (554, 'Mertz-Ritchie');
insert into distribuidora_item (id_item, distribuidora) values (555, 'Moen, Block and Pouros');
insert into distribuidora_item (id_item, distribuidora) values (556, 'Wiza, Orn and Emmerich');
insert into distribuidora_item (id_item, distribuidora) values (557, 'Rogahn-Daugherty');
insert into distribuidora_item (id_item, distribuidora) values (558, 'Bechtelar-Botsford');
insert into distribuidora_item (id_item, distribuidora) values (559, 'Marvin-Pacocha');
insert into distribuidora_item (id_item, distribuidora) values (560, 'Orn-Green');
insert into distribuidora_item (id_item, distribuidora) values (561, 'Weissnat, Rohan and Ratke');
insert into distribuidora_item (id_item, distribuidora) values (562, 'Rohan, Satterfield and Barton');
insert into distribuidora_item (id_item, distribuidora) values (563, 'Wolff, Schimmel and Williamson');
insert into distribuidora_item (id_item, distribuidora) values (564, 'McCullough Inc');
insert into distribuidora_item (id_item, distribuidora) values (565, 'Murazik LLC');
insert into distribuidora_item (id_item, distribuidora) values (566, 'Hermiston, Mayert and Franecki');
insert into distribuidora_item (id_item, distribuidora) values (567, 'Johnston and Sons');
insert into distribuidora_item (id_item, distribuidora) values (568, 'Breitenberg-Gorczany');
insert into distribuidora_item (id_item, distribuidora) values (569, 'Kozey, Rohan and Oberbrunner');
insert into distribuidora_item (id_item, distribuidora) values (570, 'Champlin-Hintz');
insert into distribuidora_item (id_item, distribuidora) values (571, 'Dicki Group');
insert into distribuidora_item (id_item, distribuidora) values (572, 'Abernathy, Bechtelar and Wilderman');
insert into distribuidora_item (id_item, distribuidora) values (573, 'Gutmann LLC');
insert into distribuidora_item (id_item, distribuidora) values (574, 'Towne Inc');
insert into distribuidora_item (id_item, distribuidora) values (575, 'Nikolaus-Kulas');
insert into distribuidora_item (id_item, distribuidora) values (576, 'Rau LLC');
insert into distribuidora_item (id_item, distribuidora) values (577, 'Paucek-Marquardt');
insert into distribuidora_item (id_item, distribuidora) values (578, 'Cummerata, Collier and Mann');
insert into distribuidora_item (id_item, distribuidora) values (579, 'Goyette and Sons');
insert into distribuidora_item (id_item, distribuidora) values (580, 'Turcotte-Medhurst');
insert into distribuidora_item (id_item, distribuidora) values (581, 'Strosin-Kling');
insert into distribuidora_item (id_item, distribuidora) values (582, 'Kessler LLC');
insert into distribuidora_item (id_item, distribuidora) values (583, 'Johns-Kling');
insert into distribuidora_item (id_item, distribuidora) values (584, 'Bergnaum, Ernser and Boyle');
insert into distribuidora_item (id_item, distribuidora) values (585, 'Nienow and Sons');
insert into distribuidora_item (id_item, distribuidora) values (586, 'Dickens-Lockman');
insert into distribuidora_item (id_item, distribuidora) values (587, 'Ziemann, Abshire and Hyatt');
insert into distribuidora_item (id_item, distribuidora) values (588, 'Batz, Goyette and Lowe');
insert into distribuidora_item (id_item, distribuidora) values (589, 'Weber Group');
insert into distribuidora_item (id_item, distribuidora) values (590, 'Emard and Sons');
insert into distribuidora_item (id_item, distribuidora) values (591, 'Weber, Nikolaus and Tremblay');
insert into distribuidora_item (id_item, distribuidora) values (592, 'Koepp-Senger');
insert into distribuidora_item (id_item, distribuidora) values (593, 'Witting LLC');
insert into distribuidora_item (id_item, distribuidora) values (594, 'Von, Jakubowski and Heidenreich');
insert into distribuidora_item (id_item, distribuidora) values (595, 'Stiedemann Group');
insert into distribuidora_item (id_item, distribuidora) values (596, 'Schroeder, Ondricka and Schneider');
insert into distribuidora_item (id_item, distribuidora) values (597, 'Morissette, Runte and Watsica');
insert into distribuidora_item (id_item, distribuidora) values (598, 'Schmidt-Conroy');
insert into distribuidora_item (id_item, distribuidora) values (599, 'Lakin Inc');
insert into distribuidora_item (id_item, distribuidora) values (600, 'Mohr, Spencer and Cole');
insert into distribuidora_item (id_item, distribuidora) values (601, 'Johnson Group');
insert into distribuidora_item (id_item, distribuidora) values (602, 'Rolfson and Sons');
insert into distribuidora_item (id_item, distribuidora) values (603, 'Schaden Group');
insert into distribuidora_item (id_item, distribuidora) values (604, 'Roberts LLC');
insert into distribuidora_item (id_item, distribuidora) values (605, 'Kuhlman-Breitenberg');
insert into distribuidora_item (id_item, distribuidora) values (606, 'Okuneva, DuBuque and Russel');
insert into distribuidora_item (id_item, distribuidora) values (607, 'McLaughlin-Weimann');
insert into distribuidora_item (id_item, distribuidora) values (608, 'Schamberger-Heaney');
insert into distribuidora_item (id_item, distribuidora) values (609, 'Rau, Schumm and Dach');
insert into distribuidora_item (id_item, distribuidora) values (610, 'Crona, Gulgowski and Deckow');
insert into distribuidora_item (id_item, distribuidora) values (611, 'Howell, Lind and Schaefer');
insert into distribuidora_item (id_item, distribuidora) values (612, 'Kohler Inc');
insert into distribuidora_item (id_item, distribuidora) values (613, 'Fay, Gerhold and Feil');
insert into distribuidora_item (id_item, distribuidora) values (614, 'Rowe, Dickinson and Waelchi');
insert into distribuidora_item (id_item, distribuidora) values (615, 'Senger-Stracke');
insert into distribuidora_item (id_item, distribuidora) values (616, 'Purdy LLC');
insert into distribuidora_item (id_item, distribuidora) values (617, 'Kreiger-Wisozk');
insert into distribuidora_item (id_item, distribuidora) values (618, 'West-Ernser');
insert into distribuidora_item (id_item, distribuidora) values (619, 'Rohan-Strosin');
insert into distribuidora_item (id_item, distribuidora) values (620, 'Dooley LLC');
insert into distribuidora_item (id_item, distribuidora) values (621, 'Weissnat, Murphy and Douglas');
insert into distribuidora_item (id_item, distribuidora) values (622, 'Huels-Wintheiser');
insert into distribuidora_item (id_item, distribuidora) values (623, 'Kemmer Group');
insert into distribuidora_item (id_item, distribuidora) values (624, 'Goyette LLC');
insert into distribuidora_item (id_item, distribuidora) values (625, 'Will and Sons');
insert into distribuidora_item (id_item, distribuidora) values (626, 'Anderson, Abbott and Brakus');
insert into distribuidora_item (id_item, distribuidora) values (627, 'Moen Inc');
insert into distribuidora_item (id_item, distribuidora) values (628, 'Ernser Group');
insert into distribuidora_item (id_item, distribuidora) values (629, 'Gislason and Sons');
insert into distribuidora_item (id_item, distribuidora) values (630, 'Mann-Daniel');
insert into distribuidora_item (id_item, distribuidora) values (631, 'Olson-Waelchi');
insert into distribuidora_item (id_item, distribuidora) values (632, 'Mosciski, Schmeler and Kunze');
insert into distribuidora_item (id_item, distribuidora) values (633, 'Shanahan and Sons');
insert into distribuidora_item (id_item, distribuidora) values (634, 'Schmitt-Champlin');
insert into distribuidora_item (id_item, distribuidora) values (635, 'Turner LLC');
insert into distribuidora_item (id_item, distribuidora) values (636, 'Bechtelar-Schneider');
insert into distribuidora_item (id_item, distribuidora) values (637, 'Gutkowski, McKenzie and Hoeger');
insert into distribuidora_item (id_item, distribuidora) values (638, 'McKenzie, Mayert and Greenfelder');
insert into distribuidora_item (id_item, distribuidora) values (639, 'Gorczany LLC');
insert into distribuidora_item (id_item, distribuidora) values (640, 'Pagac-Schimmel');
insert into distribuidora_item (id_item, distribuidora) values (641, 'Wintheiser-Littel');
insert into distribuidora_item (id_item, distribuidora) values (642, 'Ferry, Stiedemann and Cronin');
insert into distribuidora_item (id_item, distribuidora) values (643, 'Shanahan, Bednar and Schneider');
insert into distribuidora_item (id_item, distribuidora) values (644, 'Schiller Group');
insert into distribuidora_item (id_item, distribuidora) values (645, 'Ritchie-Shields');
insert into distribuidora_item (id_item, distribuidora) values (646, 'Blanda LLC');
insert into distribuidora_item (id_item, distribuidora) values (647, 'Kunze and Sons');
insert into distribuidora_item (id_item, distribuidora) values (648, 'Leannon-Wolf');
insert into distribuidora_item (id_item, distribuidora) values (649, 'Robel-Schaden');
insert into distribuidora_item (id_item, distribuidora) values (650, 'Rohan-Denesik');
insert into distribuidora_item (id_item, distribuidora) values (651, 'Grant, Farrell and Hahn');
insert into distribuidora_item (id_item, distribuidora) values (652, 'O''Hara, Weimann and Leannon');
insert into distribuidora_item (id_item, distribuidora) values (653, 'Ebert, Jacobi and Gibson');
insert into distribuidora_item (id_item, distribuidora) values (654, 'Bechtelar Inc');
insert into distribuidora_item (id_item, distribuidora) values (655, 'Waelchi and Sons');
insert into distribuidora_item (id_item, distribuidora) values (656, 'Blick LLC');
insert into distribuidora_item (id_item, distribuidora) values (657, 'Ratke, Nicolas and Homenick');
insert into distribuidora_item (id_item, distribuidora) values (658, 'Yost-Pacocha');
insert into distribuidora_item (id_item, distribuidora) values (659, 'Hoppe and Sons');
insert into distribuidora_item (id_item, distribuidora) values (660, 'Gleichner Inc');
insert into distribuidora_item (id_item, distribuidora) values (661, 'Larson-Gutkowski');
insert into distribuidora_item (id_item, distribuidora) values (662, 'Russel, Crooks and Johnson');
insert into distribuidora_item (id_item, distribuidora) values (663, 'Dicki Inc');
insert into distribuidora_item (id_item, distribuidora) values (664, 'Swift-Haag');
insert into distribuidora_item (id_item, distribuidora) values (665, 'Schneider, Leannon and Schmitt');
insert into distribuidora_item (id_item, distribuidora) values (666, 'Schuppe Group');
insert into distribuidora_item (id_item, distribuidora) values (667, 'Upton and Sons');
insert into distribuidora_item (id_item, distribuidora) values (668, 'Larson and Sons');
insert into distribuidora_item (id_item, distribuidora) values (669, 'Crist Group');
insert into distribuidora_item (id_item, distribuidora) values (670, 'Padberg, Swift and Wuckert');
insert into distribuidora_item (id_item, distribuidora) values (671, 'Ullrich Group');
insert into distribuidora_item (id_item, distribuidora) values (672, 'Sanford, Greenholt and Carter');
insert into distribuidora_item (id_item, distribuidora) values (673, 'Kozey, Skiles and Kunde');
insert into distribuidora_item (id_item, distribuidora) values (674, 'Will Inc');
insert into distribuidora_item (id_item, distribuidora) values (675, 'Lebsack and Sons');
insert into distribuidora_item (id_item, distribuidora) values (676, 'Fadel, Gulgowski and Smitham');
insert into distribuidora_item (id_item, distribuidora) values (677, 'Pacocha-King');
insert into distribuidora_item (id_item, distribuidora) values (678, 'Denesik Inc');
insert into distribuidora_item (id_item, distribuidora) values (679, 'Von, Nader and Moore');
insert into distribuidora_item (id_item, distribuidora) values (680, 'Spencer, Gerhold and Cormier');
insert into distribuidora_item (id_item, distribuidora) values (681, 'Heller-Kulas');
insert into distribuidora_item (id_item, distribuidora) values (682, 'Deckow-Okuneva');
insert into distribuidora_item (id_item, distribuidora) values (683, 'Spinka-O''Connell');
insert into distribuidora_item (id_item, distribuidora) values (684, 'Kuhic-Simonis');
insert into distribuidora_item (id_item, distribuidora) values (685, 'Ryan, Goldner and Schimmel');
insert into distribuidora_item (id_item, distribuidora) values (686, 'Rodriguez-Cole');
insert into distribuidora_item (id_item, distribuidora) values (687, 'Konopelski-Willms');
insert into distribuidora_item (id_item, distribuidora) values (688, 'Klocko LLC');
insert into distribuidora_item (id_item, distribuidora) values (689, 'Stiedemann, Murphy and Schmitt');
insert into distribuidora_item (id_item, distribuidora) values (690, 'Brekke-Jones');
insert into distribuidora_item (id_item, distribuidora) values (691, 'Fadel, Schulist and Lesch');
insert into distribuidora_item (id_item, distribuidora) values (692, 'Spencer-Pollich');
insert into distribuidora_item (id_item, distribuidora) values (693, 'Cremin and Sons');
insert into distribuidora_item (id_item, distribuidora) values (694, 'Sporer, Schroeder and Keeling');
insert into distribuidora_item (id_item, distribuidora) values (695, 'Abshire-Wyman');
insert into distribuidora_item (id_item, distribuidora) values (696, 'Grimes, Cronin and Erdman');
insert into distribuidora_item (id_item, distribuidora) values (697, 'Windler, Leffler and Williamson');
insert into distribuidora_item (id_item, distribuidora) values (698, 'Dibbert, Rohan and Rowe');
insert into distribuidora_item (id_item, distribuidora) values (699, 'MacGyver, Swift and Morissette');
insert into distribuidora_item (id_item, distribuidora) values (700, 'Jones, Monahan and Cremin');
insert into distribuidora_item (id_item, distribuidora) values (701, 'Beier, Waelchi and Bayer');
insert into distribuidora_item (id_item, distribuidora) values (702, 'Funk LLC');
insert into distribuidora_item (id_item, distribuidora) values (703, 'Heller-O''Kon');
insert into distribuidora_item (id_item, distribuidora) values (704, 'Carter LLC');
insert into distribuidora_item (id_item, distribuidora) values (705, 'Reynolds, Ward and Keebler');
insert into distribuidora_item (id_item, distribuidora) values (706, 'Kub and Sons');
insert into distribuidora_item (id_item, distribuidora) values (707, 'Von LLC');
insert into distribuidora_item (id_item, distribuidora) values (708, 'Gorczany, Willms and Ernser');
insert into distribuidora_item (id_item, distribuidora) values (709, 'Jones and Sons');
insert into distribuidora_item (id_item, distribuidora) values (710, 'Bruen, Prosacco and Hettinger');
insert into distribuidora_item (id_item, distribuidora) values (711, 'Conroy, Lowe and Ratke');
insert into distribuidora_item (id_item, distribuidora) values (712, 'Jacobi-Kirlin');
insert into distribuidora_item (id_item, distribuidora) values (713, 'Russel Group');
insert into distribuidora_item (id_item, distribuidora) values (714, 'Pollich-Nolan');
insert into distribuidora_item (id_item, distribuidora) values (715, 'Spinka Inc');
insert into distribuidora_item (id_item, distribuidora) values (716, 'Marvin Inc');
insert into distribuidora_item (id_item, distribuidora) values (717, 'Parisian Inc');
insert into distribuidora_item (id_item, distribuidora) values (718, 'Huels, Kuhn and Corkery');
insert into distribuidora_item (id_item, distribuidora) values (719, 'Pacocha, Emard and Stokes');
insert into distribuidora_item (id_item, distribuidora) values (720, 'Rath Inc');
insert into distribuidora_item (id_item, distribuidora) values (721, 'Jaskolski, D''Amore and Lockman');
insert into distribuidora_item (id_item, distribuidora) values (722, 'Herzog, Will and Yundt');
insert into distribuidora_item (id_item, distribuidora) values (723, 'Okuneva and Sons');
insert into distribuidora_item (id_item, distribuidora) values (724, 'Kris-Cummings');
insert into distribuidora_item (id_item, distribuidora) values (725, 'Altenwerth-Blanda');
insert into distribuidora_item (id_item, distribuidora) values (726, 'Durgan LLC');
insert into distribuidora_item (id_item, distribuidora) values (727, 'McCullough-Bayer');
insert into distribuidora_item (id_item, distribuidora) values (728, 'Gottlieb Inc');
insert into distribuidora_item (id_item, distribuidora) values (729, 'Crooks, Zulauf and Huels');
insert into distribuidora_item (id_item, distribuidora) values (730, 'Feeney, Dare and Bernier');
insert into distribuidora_item (id_item, distribuidora) values (731, 'Wisozk LLC');
insert into distribuidora_item (id_item, distribuidora) values (732, 'Pagac, Jacobi and Lubowitz');
insert into distribuidora_item (id_item, distribuidora) values (733, 'Mills-Crona');
insert into distribuidora_item (id_item, distribuidora) values (734, 'Frami-Kuhlman');
insert into distribuidora_item (id_item, distribuidora) values (735, 'Hagenes-Renner');
insert into distribuidora_item (id_item, distribuidora) values (736, 'Huels, Padberg and Grady');
insert into distribuidora_item (id_item, distribuidora) values (737, 'Shanahan-Weimann');
insert into distribuidora_item (id_item, distribuidora) values (738, 'Lowe, Dicki and Erdman');
insert into distribuidora_item (id_item, distribuidora) values (739, 'Homenick, Gutkowski and Greenfelder');
insert into distribuidora_item (id_item, distribuidora) values (740, 'Kshlerin and Sons');
insert into distribuidora_item (id_item, distribuidora) values (741, 'Keebler, Boehm and Ankunding');
insert into distribuidora_item (id_item, distribuidora) values (742, 'Padberg, Lemke and Hand');
insert into distribuidora_item (id_item, distribuidora) values (743, 'Barrows-Maggio');
insert into distribuidora_item (id_item, distribuidora) values (744, 'Boyer Group');
insert into distribuidora_item (id_item, distribuidora) values (745, 'Jenkins and Sons');
insert into distribuidora_item (id_item, distribuidora) values (746, 'Macejkovic Inc');
insert into distribuidora_item (id_item, distribuidora) values (747, 'Lowe, McClure and Funk');
insert into distribuidora_item (id_item, distribuidora) values (748, 'Goodwin LLC');
insert into distribuidora_item (id_item, distribuidora) values (749, 'Thiel-Kutch');
insert into distribuidora_item (id_item, distribuidora) values (750, 'Kerluke, Orn and Ortiz');
insert into distribuidora_item (id_item, distribuidora) values (751, 'Gleason-Stark');
insert into distribuidora_item (id_item, distribuidora) values (752, 'Hintz, Lehner and Rowe');
insert into distribuidora_item (id_item, distribuidora) values (753, 'Kerluke-Pouros');
insert into distribuidora_item (id_item, distribuidora) values (754, 'Harvey-Rogahn');
insert into distribuidora_item (id_item, distribuidora) values (755, 'Block Group');
insert into distribuidora_item (id_item, distribuidora) values (756, 'Wiegand and Sons');
insert into distribuidora_item (id_item, distribuidora) values (757, 'Dooley, Gutkowski and Rempel');
insert into distribuidora_item (id_item, distribuidora) values (758, 'Wiza, Barton and Wunsch');
insert into distribuidora_item (id_item, distribuidora) values (759, 'Ritchie, Marks and Schaden');
insert into distribuidora_item (id_item, distribuidora) values (760, 'Flatley, Bednar and Runolfsson');
insert into distribuidora_item (id_item, distribuidora) values (761, 'Hansen, Kohler and Senger');
insert into distribuidora_item (id_item, distribuidora) values (762, 'Roob, Douglas and Wintheiser');
insert into distribuidora_item (id_item, distribuidora) values (763, 'Doyle, Volkman and Tromp');
insert into distribuidora_item (id_item, distribuidora) values (764, 'Hettinger, Volkman and Leffler');
insert into distribuidora_item (id_item, distribuidora) values (765, 'Grady, Runte and Crona');
insert into distribuidora_item (id_item, distribuidora) values (766, 'Rau LLC');
insert into distribuidora_item (id_item, distribuidora) values (767, 'Hackett Inc');
insert into distribuidora_item (id_item, distribuidora) values (768, 'Hilll-Ondricka');
insert into distribuidora_item (id_item, distribuidora) values (769, 'Reynolds, McLaughlin and Crist');
insert into distribuidora_item (id_item, distribuidora) values (770, 'Beatty, Batz and Dach');
insert into distribuidora_item (id_item, distribuidora) values (771, 'Swaniawski, Leffler and Hahn');
insert into distribuidora_item (id_item, distribuidora) values (772, 'Mraz, Erdman and Robel');
insert into distribuidora_item (id_item, distribuidora) values (773, 'Pollich, Ritchie and Tromp');
insert into distribuidora_item (id_item, distribuidora) values (774, 'Heaney Group');
insert into distribuidora_item (id_item, distribuidora) values (775, 'Kemmer-Kertzmann');
insert into distribuidora_item (id_item, distribuidora) values (776, 'Bashirian, Towne and Beatty');
insert into distribuidora_item (id_item, distribuidora) values (777, 'Swift, Aufderhar and Cronin');
insert into distribuidora_item (id_item, distribuidora) values (778, 'Dicki Group');
insert into distribuidora_item (id_item, distribuidora) values (779, 'Roberts LLC');
insert into distribuidora_item (id_item, distribuidora) values (780, 'Hammes, O''Kon and Becker');
insert into distribuidora_item (id_item, distribuidora) values (781, 'Nader Group');
insert into distribuidora_item (id_item, distribuidora) values (782, 'Roob, Christiansen and Hermiston');
insert into distribuidora_item (id_item, distribuidora) values (783, 'Hammes-Price');
insert into distribuidora_item (id_item, distribuidora) values (784, 'Green and Sons');
insert into distribuidora_item (id_item, distribuidora) values (785, 'Feeney, Sporer and Balistreri');
insert into distribuidora_item (id_item, distribuidora) values (786, 'Pfeffer, Sawayn and Mante');
insert into distribuidora_item (id_item, distribuidora) values (787, 'McClure Inc');
insert into distribuidora_item (id_item, distribuidora) values (788, 'Murray and Sons');
insert into distribuidora_item (id_item, distribuidora) values (789, 'Stanton-Williamson');
insert into distribuidora_item (id_item, distribuidora) values (790, 'Murray Group');
insert into distribuidora_item (id_item, distribuidora) values (791, 'Carter-Corkery');
insert into distribuidora_item (id_item, distribuidora) values (792, 'Wiegand-Schiller');
insert into distribuidora_item (id_item, distribuidora) values (793, 'Kub and Sons');
insert into distribuidora_item (id_item, distribuidora) values (794, 'Hickle-Runolfsson');
insert into distribuidora_item (id_item, distribuidora) values (795, 'Bartoletti Inc');
insert into distribuidora_item (id_item, distribuidora) values (796, 'Bogan-Dare');
insert into distribuidora_item (id_item, distribuidora) values (797, 'Rohan, Ernser and Romaguera');
insert into distribuidora_item (id_item, distribuidora) values (798, 'Metz and Sons');
insert into distribuidora_item (id_item, distribuidora) values (799, 'Padberg-Murazik');
insert into distribuidora_item (id_item, distribuidora) values (800, 'Emmerich and Sons');
insert into distribuidora_item (id_item, distribuidora) values (801, 'Goyette-Corkery');
insert into distribuidora_item (id_item, distribuidora) values (802, 'Grady, Stamm and Luettgen');
insert into distribuidora_item (id_item, distribuidora) values (803, 'Schmeler-Hegmann');
insert into distribuidora_item (id_item, distribuidora) values (804, 'Maggio, Flatley and Schmitt');
insert into distribuidora_item (id_item, distribuidora) values (805, 'Beahan-Kohler');
insert into distribuidora_item (id_item, distribuidora) values (806, 'Lemke-Mayer');
insert into distribuidora_item (id_item, distribuidora) values (807, 'Bayer-Bahringer');
insert into distribuidora_item (id_item, distribuidora) values (808, 'Jenkins Inc');
insert into distribuidora_item (id_item, distribuidora) values (809, 'VonRueden-Considine');
insert into distribuidora_item (id_item, distribuidora) values (810, 'Cole-Lesch');
insert into distribuidora_item (id_item, distribuidora) values (811, 'Heaney and Sons');
insert into distribuidora_item (id_item, distribuidora) values (812, 'Beier-Conn');
insert into distribuidora_item (id_item, distribuidora) values (813, 'Batz-Ziemann');
insert into distribuidora_item (id_item, distribuidora) values (814, 'Hudson, Gutmann and Schowalter');
insert into distribuidora_item (id_item, distribuidora) values (815, 'Lowe, Jacobs and Lind');
insert into distribuidora_item (id_item, distribuidora) values (816, 'Bartoletti, Moore and Moen');
insert into distribuidora_item (id_item, distribuidora) values (817, 'Barton-Schmeler');
insert into distribuidora_item (id_item, distribuidora) values (818, 'Osinski, Rice and Nolan');
insert into distribuidora_item (id_item, distribuidora) values (819, 'McKenzie, Heathcote and Nienow');
insert into distribuidora_item (id_item, distribuidora) values (820, 'Johns-Auer');
insert into distribuidora_item (id_item, distribuidora) values (821, 'Lemke-Ullrich');
insert into distribuidora_item (id_item, distribuidora) values (822, 'Rutherford-Carter');
insert into distribuidora_item (id_item, distribuidora) values (823, 'Feil, Fahey and Bode');
insert into distribuidora_item (id_item, distribuidora) values (824, 'Walker, Adams and Harris');
insert into distribuidora_item (id_item, distribuidora) values (825, 'Koch-Kilback');
insert into distribuidora_item (id_item, distribuidora) values (826, 'Welch Group');
insert into distribuidora_item (id_item, distribuidora) values (827, 'Sawayn LLC');
insert into distribuidora_item (id_item, distribuidora) values (828, 'VonRueden Inc');
insert into distribuidora_item (id_item, distribuidora) values (829, 'Bernhard-Toy');
insert into distribuidora_item (id_item, distribuidora) values (830, 'Nienow and Sons');
insert into distribuidora_item (id_item, distribuidora) values (831, 'Collier, Pagac and Johns');
insert into distribuidora_item (id_item, distribuidora) values (832, 'Barton Group');
insert into distribuidora_item (id_item, distribuidora) values (833, 'Strosin, Streich and Fadel');
insert into distribuidora_item (id_item, distribuidora) values (834, 'Mills Inc');
insert into distribuidora_item (id_item, distribuidora) values (835, 'Lynch-Hammes');
insert into distribuidora_item (id_item, distribuidora) values (836, 'Bayer Inc');
insert into distribuidora_item (id_item, distribuidora) values (837, 'Raynor and Sons');
insert into distribuidora_item (id_item, distribuidora) values (838, 'Satterfield, Beahan and Lehner');
insert into distribuidora_item (id_item, distribuidora) values (839, 'Lynch Group');
insert into distribuidora_item (id_item, distribuidora) values (840, 'Hilll Inc');
insert into distribuidora_item (id_item, distribuidora) values (841, 'Dach-Considine');
insert into distribuidora_item (id_item, distribuidora) values (842, 'Marvin and Sons');
insert into distribuidora_item (id_item, distribuidora) values (843, 'Feil, Wiza and Ward');
insert into distribuidora_item (id_item, distribuidora) values (844, 'Goldner, Bashirian and Leannon');
insert into distribuidora_item (id_item, distribuidora) values (845, 'Gottlieb Inc');
insert into distribuidora_item (id_item, distribuidora) values (846, 'Gusikowski and Sons');
insert into distribuidora_item (id_item, distribuidora) values (847, 'Zulauf-Hauck');
insert into distribuidora_item (id_item, distribuidora) values (848, 'Will-DuBuque');
insert into distribuidora_item (id_item, distribuidora) values (849, 'Sporer-Gislason');
insert into distribuidora_item (id_item, distribuidora) values (850, 'Rodriguez Inc');
insert into distribuidora_item (id_item, distribuidora) values (851, 'Bergstrom, Metz and Koss');
insert into distribuidora_item (id_item, distribuidora) values (852, 'Parisian, Kshlerin and O''Conner');
insert into distribuidora_item (id_item, distribuidora) values (853, 'Lowe, Paucek and Macejkovic');
insert into distribuidora_item (id_item, distribuidora) values (854, 'Franecki, Mayert and Harris');
insert into distribuidora_item (id_item, distribuidora) values (855, 'Morar, Larkin and Kutch');
insert into distribuidora_item (id_item, distribuidora) values (856, 'Corwin Inc');
insert into distribuidora_item (id_item, distribuidora) values (857, 'Streich, Wisozk and Blanda');
insert into distribuidora_item (id_item, distribuidora) values (858, 'Dickens Inc');
insert into distribuidora_item (id_item, distribuidora) values (859, 'VonRueden, Walsh and Hills');
insert into distribuidora_item (id_item, distribuidora) values (860, 'Emard-Corwin');
insert into distribuidora_item (id_item, distribuidora) values (861, 'Bergstrom-Medhurst');
insert into distribuidora_item (id_item, distribuidora) values (862, 'Predovic and Sons');
insert into distribuidora_item (id_item, distribuidora) values (863, 'Frami-Goyette');
insert into distribuidora_item (id_item, distribuidora) values (864, 'Schultz-Cartwright');
insert into distribuidora_item (id_item, distribuidora) values (865, 'Quitzon-Schroeder');
insert into distribuidora_item (id_item, distribuidora) values (866, 'Bashirian, Jacobs and Koss');
insert into distribuidora_item (id_item, distribuidora) values (867, 'Weimann-Bartoletti');
insert into distribuidora_item (id_item, distribuidora) values (868, 'Kuhlman LLC');
insert into distribuidora_item (id_item, distribuidora) values (869, 'Anderson-Bayer');
insert into distribuidora_item (id_item, distribuidora) values (870, 'Nikolaus Inc');
insert into distribuidora_item (id_item, distribuidora) values (871, 'Daniel-Hackett');
insert into distribuidora_item (id_item, distribuidora) values (872, 'Mosciski, Bogan and Roob');
insert into distribuidora_item (id_item, distribuidora) values (873, 'Greenholt, Bins and Upton');
insert into distribuidora_item (id_item, distribuidora) values (874, 'Schultz-Vandervort');
insert into distribuidora_item (id_item, distribuidora) values (875, 'Jaskolski-Will');
insert into distribuidora_item (id_item, distribuidora) values (876, 'Block and Sons');
insert into distribuidora_item (id_item, distribuidora) values (877, 'Graham, Reichel and Schinner');
insert into distribuidora_item (id_item, distribuidora) values (878, 'Beer, Herzog and Gusikowski');
insert into distribuidora_item (id_item, distribuidora) values (879, 'Heller, Ryan and Brakus');
insert into distribuidora_item (id_item, distribuidora) values (880, 'Rippin, Kshlerin and Quitzon');
insert into distribuidora_item (id_item, distribuidora) values (881, 'Sawayn, Nikolaus and Rippin');
insert into distribuidora_item (id_item, distribuidora) values (882, 'Ward, Sanford and Beatty');
insert into distribuidora_item (id_item, distribuidora) values (883, 'Harris Group');
insert into distribuidora_item (id_item, distribuidora) values (884, 'Upton, Paucek and Huels');
insert into distribuidora_item (id_item, distribuidora) values (885, 'Skiles, Hegmann and Murray');
insert into distribuidora_item (id_item, distribuidora) values (886, 'Hickle, Runolfsdottir and Schaefer');
insert into distribuidora_item (id_item, distribuidora) values (887, 'Haag Group');
insert into distribuidora_item (id_item, distribuidora) values (888, 'Cormier-MacGyver');
insert into distribuidora_item (id_item, distribuidora) values (889, 'Casper-Beahan');
insert into distribuidora_item (id_item, distribuidora) values (890, 'Reilly Group');
insert into distribuidora_item (id_item, distribuidora) values (891, 'Jast and Sons');
insert into distribuidora_item (id_item, distribuidora) values (892, 'Gibson-Kunze');
insert into distribuidora_item (id_item, distribuidora) values (893, 'Davis Inc');
insert into distribuidora_item (id_item, distribuidora) values (894, 'Langworth Inc');
insert into distribuidora_item (id_item, distribuidora) values (895, 'Kilback-Schiller');
insert into distribuidora_item (id_item, distribuidora) values (896, 'Green-Schneider');
insert into distribuidora_item (id_item, distribuidora) values (897, 'Lemke-Roob');
insert into distribuidora_item (id_item, distribuidora) values (898, 'Runte Group');
insert into distribuidora_item (id_item, distribuidora) values (899, 'Gerhold, Senger and Sipes');
insert into distribuidora_item (id_item, distribuidora) values (900, 'Ryan, Nienow and Greenfelder');
insert into distribuidora_item (id_item, distribuidora) values (901, 'Nicolas-Schuster');
insert into distribuidora_item (id_item, distribuidora) values (902, 'Will Group');
insert into distribuidora_item (id_item, distribuidora) values (903, 'Conroy-Nicolas');
insert into distribuidora_item (id_item, distribuidora) values (904, 'Rau Inc');
insert into distribuidora_item (id_item, distribuidora) values (905, 'Jaskolski Inc');
insert into distribuidora_item (id_item, distribuidora) values (906, 'Stamm, Smitham and Wintheiser');
insert into distribuidora_item (id_item, distribuidora) values (907, 'Tillman Inc');
insert into distribuidora_item (id_item, distribuidora) values (908, 'Klein, Cremin and Rosenbaum');
insert into distribuidora_item (id_item, distribuidora) values (909, 'Mosciski Inc');
insert into distribuidora_item (id_item, distribuidora) values (910, 'Daugherty and Sons');
insert into distribuidora_item (id_item, distribuidora) values (911, 'Braun, Will and Cassin');
insert into distribuidora_item (id_item, distribuidora) values (912, 'Kling Inc');
insert into distribuidora_item (id_item, distribuidora) values (913, 'Kemmer LLC');
insert into distribuidora_item (id_item, distribuidora) values (914, 'Koch, Wisoky and Casper');
insert into distribuidora_item (id_item, distribuidora) values (915, 'Bauch and Sons');
insert into distribuidora_item (id_item, distribuidora) values (916, 'Franecki Group');
insert into distribuidora_item (id_item, distribuidora) values (917, 'Gerhold, Johnson and Greenfelder');
insert into distribuidora_item (id_item, distribuidora) values (918, 'Hudson, Leannon and Konopelski');
insert into distribuidora_item (id_item, distribuidora) values (919, 'Sipes-Barrows');
insert into distribuidora_item (id_item, distribuidora) values (920, 'Cummerata-Rau');
insert into distribuidora_item (id_item, distribuidora) values (921, 'Kassulke LLC');
insert into distribuidora_item (id_item, distribuidora) values (922, 'Hudson, Schinner and Koelpin');
insert into distribuidora_item (id_item, distribuidora) values (923, 'Lindgren Inc');
insert into distribuidora_item (id_item, distribuidora) values (924, 'Welch, Williamson and Greenholt');
insert into distribuidora_item (id_item, distribuidora) values (925, 'Dietrich and Sons');
insert into distribuidora_item (id_item, distribuidora) values (926, 'Hudson Group');
insert into distribuidora_item (id_item, distribuidora) values (927, 'Reichert, Beahan and Hand');
insert into distribuidora_item (id_item, distribuidora) values (928, 'Graham-Howell');
insert into distribuidora_item (id_item, distribuidora) values (929, 'Will, Bernhard and VonRueden');
insert into distribuidora_item (id_item, distribuidora) values (930, 'Howe Inc');
insert into distribuidora_item (id_item, distribuidora) values (931, 'Rowe, Kozey and Volkman');
insert into distribuidora_item (id_item, distribuidora) values (932, 'Reynolds LLC');
insert into distribuidora_item (id_item, distribuidora) values (933, 'Littel-Rau');
insert into distribuidora_item (id_item, distribuidora) values (934, 'Donnelly-Johns');
insert into distribuidora_item (id_item, distribuidora) values (935, 'Heller-Gerhold');
insert into distribuidora_item (id_item, distribuidora) values (936, 'Muller and Sons');
insert into distribuidora_item (id_item, distribuidora) values (937, 'Larson and Sons');
insert into distribuidora_item (id_item, distribuidora) values (938, 'Oberbrunner Inc');
insert into distribuidora_item (id_item, distribuidora) values (939, 'Johns Inc');
insert into distribuidora_item (id_item, distribuidora) values (940, 'Hansen, Strosin and Bahringer');
insert into distribuidora_item (id_item, distribuidora) values (941, 'Farrell Group');
insert into distribuidora_item (id_item, distribuidora) values (942, 'Kirlin LLC');
insert into distribuidora_item (id_item, distribuidora) values (943, 'Goyette-Runolfsdottir');
insert into distribuidora_item (id_item, distribuidora) values (944, 'Braun, Klocko and Rogahn');
insert into distribuidora_item (id_item, distribuidora) values (945, 'Feil-Skiles');
insert into distribuidora_item (id_item, distribuidora) values (946, 'Kuvalis Group');
insert into distribuidora_item (id_item, distribuidora) values (947, 'Jacobs-Bogisich');
insert into distribuidora_item (id_item, distribuidora) values (948, 'Miller Inc');
insert into distribuidora_item (id_item, distribuidora) values (949, 'Russel-Collier');
insert into distribuidora_item (id_item, distribuidora) values (950, 'Kuhic-Collier');
insert into distribuidora_item (id_item, distribuidora) values (951, 'Barton, Aufderhar and Macejkovic');
insert into distribuidora_item (id_item, distribuidora) values (952, 'Koss, O''Hara and Romaguera');
insert into distribuidora_item (id_item, distribuidora) values (953, 'Littel, Mosciski and Walsh');
insert into distribuidora_item (id_item, distribuidora) values (954, 'Kilback, Barrows and Howe');
insert into distribuidora_item (id_item, distribuidora) values (955, 'Dicki, Davis and Rutherford');
insert into distribuidora_item (id_item, distribuidora) values (956, 'Rippin and Sons');
insert into distribuidora_item (id_item, distribuidora) values (957, 'Ratke Group');
insert into distribuidora_item (id_item, distribuidora) values (958, 'Bergnaum, Tremblay and Zboncak');
insert into distribuidora_item (id_item, distribuidora) values (959, 'Leannon LLC');
insert into distribuidora_item (id_item, distribuidora) values (960, 'Konopelski and Sons');
insert into distribuidora_item (id_item, distribuidora) values (961, 'Farrell-Kuhic');
insert into distribuidora_item (id_item, distribuidora) values (962, 'Beatty Group');
insert into distribuidora_item (id_item, distribuidora) values (963, 'Koelpin-Mohr');
insert into distribuidora_item (id_item, distribuidora) values (964, 'Nitzsche Group');
insert into distribuidora_item (id_item, distribuidora) values (965, 'Ebert, Pouros and O''Keefe');
insert into distribuidora_item (id_item, distribuidora) values (966, 'Emmerich Inc');
insert into distribuidora_item (id_item, distribuidora) values (967, 'Kuhlman-Jaskolski');
insert into distribuidora_item (id_item, distribuidora) values (968, 'Kovacek-D''Amore');
insert into distribuidora_item (id_item, distribuidora) values (969, 'Padberg, Larson and Luettgen');
insert into distribuidora_item (id_item, distribuidora) values (970, 'Waelchi Inc');
insert into distribuidora_item (id_item, distribuidora) values (971, 'Hessel, Upton and Crist');
insert into distribuidora_item (id_item, distribuidora) values (972, 'Labadie, Bailey and Jacobs');
insert into distribuidora_item (id_item, distribuidora) values (973, 'Miller, Bauch and Brown');
insert into distribuidora_item (id_item, distribuidora) values (974, 'Kertzmann, Yost and Ferry');
insert into distribuidora_item (id_item, distribuidora) values (975, 'Bogan Group');
insert into distribuidora_item (id_item, distribuidora) values (976, 'Cartwright-Tromp');
insert into distribuidora_item (id_item, distribuidora) values (977, 'Grimes-Lemke');
insert into distribuidora_item (id_item, distribuidora) values (978, 'Fadel-Miller');
insert into distribuidora_item (id_item, distribuidora) values (979, 'Dickinson-Connelly');
insert into distribuidora_item (id_item, distribuidora) values (980, 'Russel, Gerhold and Walter');
insert into distribuidora_item (id_item, distribuidora) values (981, 'Kertzmann, Schmidt and Schimmel');
insert into distribuidora_item (id_item, distribuidora) values (982, 'Ziemann-Leffler');
insert into distribuidora_item (id_item, distribuidora) values (983, 'Murazik and Sons');
insert into distribuidora_item (id_item, distribuidora) values (984, 'Swift, Romaguera and Tremblay');
insert into distribuidora_item (id_item, distribuidora) values (985, 'Barton, Hackett and Weber');
insert into distribuidora_item (id_item, distribuidora) values (986, 'Oberbrunner, O''Reilly and West');
insert into distribuidora_item (id_item, distribuidora) values (987, 'Haley-Mraz');
insert into distribuidora_item (id_item, distribuidora) values (988, 'O''Keefe and Sons');
insert into distribuidora_item (id_item, distribuidora) values (989, 'Jones, Sauer and Labadie');
insert into distribuidora_item (id_item, distribuidora) values (990, 'Cartwright, Yost and Wilderman');
insert into distribuidora_item (id_item, distribuidora) values (991, 'Little and Sons');
insert into distribuidora_item (id_item, distribuidora) values (992, 'Kirlin and Sons');
insert into distribuidora_item (id_item, distribuidora) values (993, 'Satterfield-Walter');
insert into distribuidora_item (id_item, distribuidora) values (994, 'Moen and Sons');
insert into distribuidora_item (id_item, distribuidora) values (995, 'Bauch-Shields');
insert into distribuidora_item (id_item, distribuidora) values (996, 'Ernser, Paucek and Nienow');
insert into distribuidora_item (id_item, distribuidora) values (997, 'Johnston, Pacocha and Lind');
insert into distribuidora_item (id_item, distribuidora) values (998, 'Bartoletti-Kilback');
insert into distribuidora_item (id_item, distribuidora) values (999, 'Goodwin-Nader');
insert into distribuidora_item (id_item, distribuidora) values (1000, 'Koss-Fisher');